<?php

namespace App\Models\Proxies\__CG__\App\Models\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Korisnik extends \App\Models\Entities\Korisnik implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Korisnik' . "\0" . 'idkorisnik', '' . "\0" . 'App\\Models\\Entities\\Korisnik' . "\0" . 'kime', '' . "\0" . 'App\\Models\\Entities\\Korisnik' . "\0" . 'sifra', '' . "\0" . 'App\\Models\\Entities\\Korisnik' . "\0" . 'email', '' . "\0" . 'App\\Models\\Entities\\Korisnik' . "\0" . 'tipkorisnika', '' . "\0" . 'App\\Models\\Entities\\Korisnik' . "\0" . 'idlista', '' . "\0" . 'App\\Models\\Entities\\Korisnik' . "\0" . 'idradnje'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Korisnik' . "\0" . 'idkorisnik', '' . "\0" . 'App\\Models\\Entities\\Korisnik' . "\0" . 'kime', '' . "\0" . 'App\\Models\\Entities\\Korisnik' . "\0" . 'sifra', '' . "\0" . 'App\\Models\\Entities\\Korisnik' . "\0" . 'email', '' . "\0" . 'App\\Models\\Entities\\Korisnik' . "\0" . 'tipkorisnika', '' . "\0" . 'App\\Models\\Entities\\Korisnik' . "\0" . 'idlista', '' . "\0" . 'App\\Models\\Entities\\Korisnik' . "\0" . 'idradnje'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Korisnik $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdkorisnik()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdkorisnik();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdkorisnik', []);

        return parent::getIdkorisnik();
    }

    /**
     * {@inheritDoc}
     */
    public function setKime($kime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKime', [$kime]);

        return parent::setKime($kime);
    }

    /**
     * {@inheritDoc}
     */
    public function getKime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKime', []);

        return parent::getKime();
    }

    /**
     * {@inheritDoc}
     */
    public function setSifra($sifra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSifra', [$sifra]);

        return parent::setSifra($sifra);
    }

    /**
     * {@inheritDoc}
     */
    public function getSifra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSifra', []);

        return parent::getSifra();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipkorisnika($tipkorisnika)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipkorisnika', [$tipkorisnika]);

        return parent::setTipkorisnika($tipkorisnika);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipkorisnika()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipkorisnika', []);

        return parent::getTipkorisnika();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdlistum(\App\Models\Entities\Lista $idlistum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdlistum', [$idlistum]);

        return parent::addIdlistum($idlistum);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdlistum(\App\Models\Entities\Lista $idlistum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdlistum', [$idlistum]);

        return parent::removeIdlistum($idlistum);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdlista()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdlista', []);

        return parent::getIdlista();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdradnje(\App\Models\Entities\Radnja $idradnje = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdradnje', [$idradnje]);

        return parent::setIdradnje($idradnje);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdradnje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdradnje', []);

        return parent::getIdradnje();
    }

}
