<?php

namespace App\Models\Proxies\__CG__\App\Models\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Radnja extends \App\Models\Entities\Radnja implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Radnja' . "\0" . 'idradnje', '' . "\0" . 'App\\Models\\Entities\\Radnja' . "\0" . 'naziv', '' . "\0" . 'App\\Models\\Entities\\Radnja' . "\0" . 'sirina', '' . "\0" . 'App\\Models\\Entities\\Radnja' . "\0" . 'duzina', '' . "\0" . 'App\\Models\\Entities\\Radnja' . "\0" . 'pib', '' . "\0" . 'App\\Models\\Entities\\Radnja' . "\0" . 'radnidani', '' . "\0" . 'App\\Models\\Entities\\Radnja' . "\0" . 'radnovreme', '' . "\0" . 'App\\Models\\Entities\\Radnja' . "\0" . 'idpredstavnika', '' . "\0" . 'App\\Models\\Entities\\Radnja' . "\0" . 'idProdaja'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Radnja' . "\0" . 'idradnje', '' . "\0" . 'App\\Models\\Entities\\Radnja' . "\0" . 'naziv', '' . "\0" . 'App\\Models\\Entities\\Radnja' . "\0" . 'sirina', '' . "\0" . 'App\\Models\\Entities\\Radnja' . "\0" . 'duzina', '' . "\0" . 'App\\Models\\Entities\\Radnja' . "\0" . 'pib', '' . "\0" . 'App\\Models\\Entities\\Radnja' . "\0" . 'radnidani', '' . "\0" . 'App\\Models\\Entities\\Radnja' . "\0" . 'radnovreme', '' . "\0" . 'App\\Models\\Entities\\Radnja' . "\0" . 'idpredstavnika', '' . "\0" . 'App\\Models\\Entities\\Radnja' . "\0" . 'idProdaja'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Radnja $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdradnje()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdradnje();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdradnje', []);

        return parent::getIdradnje();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaziv($naziv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaziv', [$naziv]);

        return parent::setNaziv($naziv);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaziv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaziv', []);

        return parent::getNaziv();
    }

    /**
     * {@inheritDoc}
     */
    public function setSirina($sirina)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSirina', [$sirina]);

        return parent::setSirina($sirina);
    }

    /**
     * {@inheritDoc}
     */
    public function getSirina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSirina', []);

        return parent::getSirina();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuzina($duzina)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuzina', [$duzina]);

        return parent::setDuzina($duzina);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuzina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuzina', []);

        return parent::getDuzina();
    }

    /**
     * {@inheritDoc}
     */
    public function setPib($pib)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPib', [$pib]);

        return parent::setPib($pib);
    }

    /**
     * {@inheritDoc}
     */
    public function getPib()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPib', []);

        return parent::getPib();
    }

    /**
     * {@inheritDoc}
     */
    public function setRadnidani($radnidani)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRadnidani', [$radnidani]);

        return parent::setRadnidani($radnidani);
    }

    /**
     * {@inheritDoc}
     */
    public function getRadnidani()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRadnidani', []);

        return parent::getRadnidani();
    }

    /**
     * {@inheritDoc}
     */
    public function setRadnovreme($radnovreme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRadnovreme', [$radnovreme]);

        return parent::setRadnovreme($radnovreme);
    }

    /**
     * {@inheritDoc}
     */
    public function getRadnovreme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRadnovreme', []);

        return parent::getRadnovreme();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpredstavnika(\App\Models\Entities\Korisnik $idpredstavnika = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpredstavnika', [$idpredstavnika]);

        return parent::setIdpredstavnika($idpredstavnika);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpredstavnika()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpredstavnika', []);

        return parent::getIdpredstavnika();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdProdaja(\App\Models\Entities\Prodaje $idProdaje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdProdaja', [$idProdaje]);

        return parent::addIdProdaja($idProdaje);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdProdaja(\App\Models\Entities\Prodaje $idProdaja)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdProdaja', [$idProdaja]);

        return parent::removeIdProdaja($idProdaja);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProdaja()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProdaja', []);

        return parent::getIdProdaja();
    }

}
